# Generated by Django 4.2.7 on 2023-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_order',
            field=models.FloatField(default=0.0),
        ),
    ]
