# Generated by Django 4.2.7 on 2023-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password_confirm',
            field=models.CharField(max_length=200),
        ),
    ]
