# Generated by Django 4.2.7 on 2023-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(default='user@hui.io', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
